In [1]:
import torch
import numpy as np
import pandas as pd

In [13]:
def relu(x):
    return np.clip(x, a_min=0, a_max=None)

relu(np.array([-2, -1, 0, 1, 2]))

array([0, 0, 0, 1, 2])

In [7]:
def sigmoid(x): 
    return 1 / (1 + np.exp(-x))

In [9]:
sigmoid(np.array([-2, -1, 0, 1, 2]))

array([0.11920292, 0.26894142, 0.5       , 0.73105858, 0.88079708])

tanh(x) = 2 * sigmoid(2x) — 1

In [14]:
np.tanh(np.array([-2, -1, 0, 1, 2]))

array([-0.96402758, -0.76159416,  0.        ,  0.76159416,  0.96402758])