In [16]:
import torch
import numpy as np
import pandas as pd
from scipy.special import softmax

In [13]:
def relu(x):
    return np.clip(x, a_min=0, a_max=None)

relu(np.array([-2, -1, 0, 1, 2]))

array([0, 0, 0, 1, 2])

In [7]:
def sigmoid(x): 
    return 1 / (1 + np.exp(-x))

In [9]:
sigmoid(np.array([-2, -1, 0, 1, 2]))

array([0.11920292, 0.26894142, 0.5       , 0.73105858, 0.88079708])

tanh(x) = 2 * sigmoid(2x) — 1

In [14]:
np.tanh(np.array([-2, -1, 0, 1, 2]))

array([-0.96402758, -0.76159416,  0.        ,  0.76159416,  0.96402758])

Softmax

In [17]:
softmax(np.array([-2, -1, 0, 1, 2]))

array([0.01165623, 0.03168492, 0.08612854, 0.23412166, 0.63640865])

In [19]:
softmax(np.array([[-2, -1, 0], [-3, 2, 3]]), axis=0)

array([[0.73105858, 0.04742587, 0.04742587],
       [0.26894142, 0.95257413, 0.95257413]])

In [20]:
softmax(np.array([[-2, -1, 0], [-3, 2, 3]]), axis=1)

array([[0.09003057, 0.24472847, 0.66524096],
       [0.00180884, 0.26845495, 0.72973621]])